name: lint-on-push

on: [push]

jobs:
  lint-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Lint with Black - should check all python files in dependency
      - name: Run Black
        run: |
          python3 -m black --check . 

